apiVersion: carto.run/v1alpha1
kind: ClusterTemplate
metadata:
  name: app-deploy
spec:
  template:
    apiVersion: serving.knative.dev/v1
    kind: Service
    metadata:
      name: tanzu-java-web-app-wwc
    spec:
      template:
        metadata:
          annotations:
            autoscaling.knative.dev/maxScale: "1"
            autoscaling.knative.dev/minScale: "1"
        spec:
          containerConcurrency: 0
          containers:
              image: $(images.image.image)$
              name: workload
              securityContext:
                runAsUser: 1000
          serviceAccountName: default
          timeoutSeconds: 300
